USE [master]
GO

/****** Object:  Database [NpvDB]    Script Date: 8/9/2019 3:50:36 PM ******/
CREATE DATABASE [NpvDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NpvDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\NpvDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NpvDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\NpvDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [NpvDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NpvDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NpvDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NpvDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NpvDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NpvDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NpvDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [NpvDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NpvDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NpvDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NpvDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NpvDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NpvDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NpvDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NpvDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NpvDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NpvDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NpvDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NpvDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NpvDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NpvDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NpvDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NpvDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NpvDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NpvDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NpvDB] SET  MULTI_USER 
GO

ALTER DATABASE [NpvDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NpvDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NpvDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NpvDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NpvDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NpvDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NpvDB] SET  READ_WRITE 
GO


--=== Create Tables

USE [NpvDB]
GO

/****** Object:  Table [dbo].[Calculation]    Script Date: 8/9/2019 3:52:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Calculation](
	[CalculationID] [int] IDENTITY(1,1) NOT NULL,
	[LowerBoundDiscountRate] [float] NOT NULL,
	[UpperBoundDiscountRate] [float] NOT NULL,
	[DiscountRateIncrement] [float] NOT NULL,
	[InitialInvestment] [float] NOT NULL,
 CONSTRAINT [PK_Calculation] PRIMARY KEY CLUSTERED 
(
	[CalculationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [NpvDB]
GO

/****** Object:  Table [dbo].[CashFlow]    Script Date: 8/9/2019 3:52:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CashFlow](
	[CashFlowID] [int] IDENTITY(1,1) NOT NULL,
	[CashFlowValue] [float] NOT NULL,
	[CalculationID] [int] NOT NULL,
 CONSTRAINT [PK_CashFlow] PRIMARY KEY CLUSTERED 
(
	[CashFlowID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO