//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpvCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashFlow
    {
        public int CashFlowID { get; set; }
        public double CashFlowValue { get; set; }
        public int CalculationID { get; set; }
    }
}
